### ISSUE TITLE
Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes

### ISSUE THREAD

**Issue by AVVS** [dropbox/amqp-coffee#42]
iojs v2.4.0

```js
mservice-arkmail-api-0 (err): RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
mservice-arkmail-api-0 (err):     at checked (buffer.js:174:11)
mservice-arkmail-api-0 (err):     at fromNumber (buffer.js:57:51)
mservice-arkmail-api-0 (err):     at new Buffer (buffer.js:42:5)
mservice-arkmail-api-0 (err):     at AMQPParser.header (/opt/arkmail-backend/node_modules/arkmail-backend/node_modules/mservice-utils/node_modules/amqp-coffee/bin/src/lib/AMQPParser.js:47:28)
mservice-arkmail-api-0 (err):     at AMQPParser.execute (/opt/arkmail-backend/node_modules/arkmail-backend/node_modules/mservice-utils/node_modules/amqp-coffee/bin/src/lib/AMQPParser.js:30:33)
mservice-arkmail-api-0 (err):     at Socket.<anonymous> (/opt/arkmail-backend/node_modules/arkmail-backend/node_modules/mservice-utils/node_modules/amqp-coffee/bin/src/lib/Connection.js:419:31)
mservice-arkmail-api-0 (err):     at emitOne (events.js:77:13)
mservice-arkmail-api-0 (err):     at Socket.emit (events.js:169:7)
mservice-arkmail-api-0 (err):     at readableAddChunk (_stream_readable.js:146:16)
mservice-arkmail-api-0 (err):     at Socket.Readable.push (_stream_readable.js:110:10)
mservice-arkmail-api-0 (err):     at TCP.onread (net.js:521:20)
```

**Comment by barshow** [comment]
does this happen a lot?  I looked at the code and it seems ok, it even checks to make sure the size is less that the servers specified max frame size.  Does this occur when the process is next to out of memory or randomly?

**Comment by AVVS** [comment]
This is quite a weird case for me. It only happens on a server, which is 25ms away from the server. It happened many times over a day, but sometimes never happened at all.

On top of it same server would go nuts with close event firing every 2 seconds with immediate reconnect right after. However heartbeat is at 10s default. No other server has this issue, however.

**Comment by AVVS** [comment]
Havent happened after recent updates, so not sure if its still a problem, keeping an eye on it though
